#!/bin/bash

# Author:         Subhayan Dasgupta
# Date Created:   5/1/24
# Date Modified:  6/1/24

# Description:
# Install Docker Engine on Ubuntu, use 64-bit version of Mantic 23.10, Lunar 23.04, Jammy 22.04 (LTS) or Focal 20.04 (LTS).

# Usage:
# This shell script is used to install Docker Engine on Ubuntu based Linux hosts. Use "chmod 744" permission # to scope the read, write and execute permission to the logged in user only.
# Acknowledgement: https://docs.docker.com/engine/install/ubuntu/

set -e

# Before you can install Docker Engine, you need to uninstall any conflicting packages.
for pkg in docker.io docker-doc docker-compose docker-compose-v2 podman-docker containerd runc; do sudo apt-get remove $pkg; done

# Install using the apt repository
# Set up Docker's apt repository.
# Add Docker's official GPG key:
sudo apt-get -y update
sudo apt-get install -y ca-certificates curl gnupg
sudo install -m 0755 -d /etc/apt/keyrings
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
sudo chmod a+r /etc/apt/keyrings/docker.gpg

# Add the repository to Apt sources:
echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
  $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
  sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
sudo apt-get -y update

# To install the latest version, run:
sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

# Verify that the Docker Engine installation is successful by running the hello-world image.
sudo docker run hello-world
