#!/bin/bash

# Author:         Subhayan Dasgupta
# Date Created:   5/1/24
# Date Modified:  6/1/24

# Description:
# Eclipse Temurin Package Names
# The following name schema is being used:
# temurin-<version>-jdk
# e.g temurin-17-jdk or temurin-8-jdk

# Usage:
# This shell script is used to install adoptium's openjdk LTS on Ubuntu based Linux hosts. Use "chmod 744" 
# permission to scope the read, write and execute permission to the logged in user only.
# Acknowledgement: https://adoptium.net/en-GB/installation/linux/

set -e

# Ensure the necessary packages are present:
apt-get update -y
apt install -y wget apt-transport-https

# Download the Eclipse Adoptium GPG key:
wget -qO - https://packages.adoptium.net/artifactory/api/gpg/key/public | gpg --dearmor | tee /etc/apt/trusted.gpg.d/adoptium.gpg > /dev/null

# Configure the Eclipse Adoptium apt repository. To check the full list of versions supported take a look at # the list in the tree at https://packages.adoptium.net/ui/native/deb/dists/.
echo "deb https://packages.adoptium.net/artifactory/deb $(awk -F= '/^VERSION_CODENAME/{print$2}' /etc/os-release) main" | tee /etc/apt/sources.list.d/adoptium.list

# Install the Temurin version you require:
apt update -y # update if you haven't already
apt install -y temurin-17-jdk # openjdk 17 LTS

# checking the installed version
java -version
